# Generated by Django 4.0.4 on 2022-04-27 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Блог', 'verbose_name_plural': 'Блоги'},
        ),
        migrations.AlterModelOptions(
            name='blogarticle',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='blogauthor',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='blogmoderator',
            options={'verbose_name': 'Модератор', 'verbose_name_plural': 'Модераторы'},
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Таблица блогов',
        ),
        migrations.AlterModelTable(
            name='blogarticle',
            table='Статьи блога',
        ),
        migrations.AlterModelTable(
            name='blogauthor',
            table='Авторы блога',
        ),
        migrations.AlterModelTable(
            name='blogmoderator',
            table='Модераторы блога',
        ),
    ]
