# Generated by Django 4.0.4 on 2022-04-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(db_index=True, max_length=20, verbose_name='Имя автора')),
                ('biography', models.TextField(max_length=4000)),
                ('authors_news', models.ManyToManyField(to='news.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='author_news',
            field=models.ManyToManyField(to='news.author'),
        ),
    ]
