# Generated by Django 4.0.4 on 2022-04-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_title_author_news_author_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='authors_news',
            field=models.ManyToManyField(to='news.news', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='news',
            name='author_news',
            field=models.ManyToManyField(to='news.author', verbose_name='Автор'),
        ),
    ]
