# Generated by Django 4.0.4 on 2022-04-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_author_author_last_name_author_author_second_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft'), ('r', 'review')], default='d', max_length=1, verbose_name='Статус новости'),
        ),
    ]
