# Generated by Django 4.0.4 on 2022-04-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment_user_alter_comment_user_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='Таблица комментариев',
        ),
        migrations.AlterModelTable(
            name='news',
            table='Таблица новостей',
        ),
    ]
