# Generated by Django 4.0.4 on 2022-04-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_comment_user_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['from_news'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
