# Generated by Django 4.0.4 on 2022-04-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_comment_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['author_name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='Таблица авторов',
        ),
    ]
