# Generated by Django 4.0.4 on 2022-04-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_author_options_alter_author_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'permissions': (('permit', 'разрешение на публикацию'),), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
