# Generated by Django 4.0.4 on 2022-04-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_news_author_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['created_at'], 'permissions': [('permit', 'разрешение на публикацию'), ('testperm', 'тестовое разрешение')], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
