# Generated by Django 4.0.4 on 2022-04-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='slug', max_length=25),
        ),
    ]
