# Generated by Django 4.0.4 on 2022-04-20 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesForNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to="<method 'date' of 'datetime.datetime' objects>/<method 'time' of 'datetime.datetime' objects>/")),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
