# Generated by Django 4.0.4 on 2022-04-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_filesfornews'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filesfornews',
            table='Таблица файлов для новостей',
        ),
    ]
