# Generated by Django 4.0.4 on 2022-04-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_alter_filesfornews_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesfornews',
            name='file',
            field=models.FileField(max_length=2000, upload_to='files/'),
        ),
    ]
