# Generated by Django 4.0.4 on 2022-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_alter_filesfornews_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at'], 'permissions': [('permit', 'разрешение на публикацию'), ('testperm', 'тестовое разрешение')], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='filesfornews',
            name='file',
            field=models.FileField(max_length=2000, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft'), ('r', 'review')], default='r', max_length=1, verbose_name='Статус новости'),
        ),
    ]
