# Generated by Django 4.0.4 on 2022-04-21 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_alter_news_options_alter_filesfornews_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesfornews',
            name='file',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='filesfornews',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
