# Generated by Django 4.0.4 on 2022-04-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='librarybook',
            table='Книги библиотеки',
        ),
        migrations.AlterModelTable(
            name='librarybookauthor',
            table='Авторы книг библиотеки',
        ),
    ]
