# Generated by Django 4.0.4 on 2022-04-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_profile_discount_card_number_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='news_counter',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Опубликовано новостей'),
        ),
        migrations.AddField(
            model_name='profile',
            name='verification_flag',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Флаг верификации'),
        ),
    ]
