# Generated by Django 4.0.4 on 2022-04-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_remove_profile_date_of_birth_profile_news_counter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['news_counter']},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Профиль пользователя',
        ),
    ]
