# Generated by Django 4.0.4 on 2022-04-17 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_profile_options_alter_profile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['news_counter'], 'permissions': (('verification_user', 'Верификация пользователя'),)},
        ),
    ]
